### ISSUE TITLE
Extending RQuery?

### ISSUE THREAD

**Issue by scruffles** [percyhanna/rquery#12]
First off, this is a great library.  This is what I was expecting to see when I looked at React TestUtils the first time.  Thank you!

I'm interested in adding some convenience functions to RQuery.  I don't think everyone will need them, so I didn't really want to send a pull request.  I was thinking of having something more like a jquery extension.  My question, is this intended to be extendable?  I seem to be able to add functions easily enough like this:

$R.rquery.prototype.innerHTML = -> (this.components.map (c) -> c.getDOMNode().innerHTML).join('')
now I can use my function like so:

$comp.find('.renderedWikiText').innerHTML()

I just didn't want to find out I'm hacking in an unexpected way and not be able to upgrade because you closed access to the prototype.  Any other downsides to this?

**Comment by percyhanna** [comment]
I think it'd be very reasonable to add a [`_.mixin`](http://underscorejs.org/#mixin) type function to extend the `rquery` object.

I also think that adding `$r.html()` would be very complementary to `$r.text()`. :)
