### ISSUE TITLE
find with css-style selectors

### ISSUE THREAD

**Issue by BlueVajra** [percyhanna/rquery#18]
It seems the selectors work with elements, for instance "div a" but normal css selectors like ".button.delete" don't seem to work with find. Are there plans for this?

**Comment by percyhanna** [comment]
`rquery` supports [class](https://github.com/percyhanna/rquery#dom-class-selector) and [attribute](https://github.com/percyhanna/rquery#attribute-selector) selectors, as well as union (`a, b`), descendent (`a b`), and child (`a > b`) syntax.

If these aren't working for you then there's potentially something else going on. As noted in #14, `rquery` doesn't currently support shallow rendering.

**Comment by BlueVajra** [comment]
does `rquery` class selectors only allow one class? For instance, in my `rquery` test, I examine the component and see these props

```
props:
      { className: 'button disabled',
        onClick: [Object],
        children: [Object] }
```

when I try either of these I get true

```
expect($component.find('.button')).to.have.length(1);
expect($component.find('.disabled')).to.have.length(1);
```

yet when I try to use the following, I get false

```
expect($component.find('.button.disabled')).to.have.length(1);
```

I tried the union syntax you mentioned `('.button, .disabled')`, but no luck there

**Comment by percyhanna** [comment]
Hmm, it should support chained class names. See [test here](https://github.com/percyhanna/rquery/blob/master/test/selectors.spec.js#L194-L206).

**Comment by BlueVajra** [comment]
ok, thanks... must be something weird going on... I will dig around and see what I can figure out.

**Comment by percyhanna** [comment]
Is `className` being passed to a composite component? If so, that might be the problem.

**Comment by percyhanna** [comment]
For example:
- DOM component: `<div className="my-class" />`
- Composite component: `<MyComponent className="my-class" />`

It could be that `.my-class` won't match `className` on a composite component, I don't think there's a test for that scenario.

**Comment by percyhanna** [comment]
Closing for now until more details are provided.
