### ISSUE TITLE
Shouldn't get() return the actual underlying component?

### ISSUE THREAD

**Issue by valscion** [percyhanna/rquery#2]
I looked at your specs and I see that you've implemented [`get()` to return a `rquery` component](https://github.com/percyhanna/rquery/blob/3124911f4acc17a7b8cb1d9b48db7672e769d50b/test/rquery.spec.js#L187) so that it works identical to the array lookup. I got a little confused, as I was expecting `get()` to work similarly to [jQuery's `get()`](http://api.jquery.com/get/) — that is, returning the underlying React Component.

I believe it might be better to mimic the API of jQuery in this case and return the React component instead of the `rquery` instance. What do you think?

**Comment by percyhanna** [comment]
That makes sense. Overall I'd like to keep as many similarities to jQuery as possible, where it makes sense anyway. I'll get this changed up shortly.

**Comment by percyhanna** [comment]
Addressed in 28192c6857e244c506e5419f67f7c2e001248f20, will merge that into `master` for a v1 release that will be coming up shortly.
