### ISSUE TITLE
npm@latest gives version 2.0.9 of the library

### ISSUE THREAD

**Issue by valscion** [percyhanna/rquery#35]
Hi,

I've really enjoyed using rquery for a long time now in our quite large project, and it's been working splendidly, thanks!

I just tried to upgrade my version of `rquery` with `npm install --save-dev rquery@latest` and it seems that you've published version 2.0.9, probably accidentally, as the "latest" module.

https://docs.npmjs.com/cli/dist-tag#purpose

> By default, the `latest` tag is used by npm to identify the current version of a package, and `npm install <pkg>` (without any `@<version>` or `@<tag>` specifier) installs the latest tag. Typically, projects only use the `latest` tag for stable release versions, and use other tags for unstable versions such as prereleases.

When publishing new versions, you probably need to set the [`--tag` option manually](https://docs.npmjs.com/cli/publish) when running `npm publish` with 2.x and 3.x branches :)

**Comment by percyhanna** [comment]
Thanks, Vesa. I wasn't even aware of this behaviour in npm. I have updated the `latest` tag to point to version 4.2.0, and will remember to use the `--tag` option for patch releases on older branches.
