### ISSUE TITLE
Can't find child component using Shallow Rendering.

### ISSUE THREAD

**Issue by BernardDoherty** [percyhanna/rquery#36]
Hello,

I can't find a component using Shallow Rendering with $R(component).find('MyComponentName').
It just returns a rquery object with a length of zero. Does this work with Shallow Rendering? 
Thanks!

**Comment by percyhanna** [comment]
Shallow rendering has been supported since #29, which was released as version 4.1.0. Can you provide a small reproducible example showing the failure? It's possible the tests are missing a specific scenario, but as far as I know it works properly.

**Comment by BernardDoherty** [comment]
Hi, thank for the reply. I was able to get it working. Our team is now using rquery. Very helpful in speeding up our testing!
