### ISSUE TITLE
Lodash is undefined in nodejs

### ISSUE THREAD

**Issue by dignifiedquire** [percyhanna/rquery#6]
```
ReferenceError: _ is not defined
      at getDescendents (/project/path/node_modules/rquery/rquery.js:25:12)
```

Looks like you need to `_ = require('lodash')` in the node js module setup, and should be added as a real dependency in `package.json`

**Comment by okonet** [comment]
+1

Just ran into this one with webpack. Could we have #7 merged and published please?

**Comment by percyhanna** [comment]
Fixed in `1.1.0`

**Comment by percyhanna** [comment]
Sorry for the delay, notifications went missing as I was on vacation last week.

**Comment by okonet** [comment]
:+1:
